//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JitsiMeetOutlook.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("meet.jit.si")]
        public string Domain {
            get {
                return ((string)(this["Domain"]));
            }
            set {
                this["Domain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool requireDisplayName {
            get {
                return ((bool)(this["requireDisplayName"]));
            }
            set {
                this["requireDisplayName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool startWithAudioMuted {
            get {
                return ((bool)(this["startWithAudioMuted"]));
            }
            set {
                this["startWithAudioMuted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool startWithVideoMuted {
            get {
                return ((bool)(this["startWithVideoMuted"]));
            }
            set {
                this["startWithVideoMuted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string roomID {
            get {
                return ((string)(this["roomID"]));
            }
            set {
                this["roomID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string installDirectory {
            get {
                return ((string)(this["installDirectory"]));
            }
            set {
                this["installDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sv")]
        public string language {
            get {
                return ((string)(this["language"]));
            }
            set {
                this["language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string randomRoomIdGeneratorMode {
            get {
                return ((string)(this["randomRoomIdGeneratorMode"]));
            }
            set {
                this["randomRoomIdGeneratorMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.jitsi.net/conferenceMapper")]
        public string conferenceMapperEndpoint {
            get {
                return ((string)(this["conferenceMapperEndpoint"]));
            }
            set {
                this["conferenceMapperEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.jitsi.net/phoneNumberList")]
        public string phoneNumberListEndpoint {
            get {
                return ((string)(this["phoneNumberListEndpoint"]));
            }
            set {
                this["phoneNumberListEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string conferenceSchedulerEndpoint {
            get {
                return ((string)(this["conferenceSchedulerEndpoint"]));
            }
            set {
                this["conferenceSchedulerEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string conferenceSchedulerEndpointSecret {
            get {
                return ((string)(this["conferenceSchedulerEndpointSecret"]));
            }
            set {
                this["conferenceSchedulerEndpointSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool disableCustomRoomId {
            get {
                return ((bool)(this["disableCustomRoomId"]));
            }
            set {
                this["disableCustomRoomId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enablePhoneNumbers {
            get {
                return ((bool)(this["enablePhoneNumbers"]));
            }
            set {
                this["enablePhoneNumbers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string serviceName {
            get {
                return ((string)(this["serviceName"]));
            }
            set {
                this["serviceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.google.se/")]
        public string supportUrl {
            get {
                return ((string)(this["supportUrl"]));
            }
            set {
                this["supportUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>Microphone</string>
  <string>Camera</string>
  <string>Screenshare</string>
  <string>Chat</string>
  <string>Raise Hand</string>
  <string>Participants Pane</string>
  <string>Toggle Tile View</string>
  <string>Toggle Camera</string>
  <string>Leave Meeting</string>
  <string>Profile</string>
  <string>Invite people</string>
  <string>Performance settings</string>
  <string>View Full Screen</string>
  <string>Security Options</string>
  <string>Closed Caption</string>
  <string>Recording</string>
  <string>Highlight Moments (when Recording)</string>
  <string>Live Streaming</string>
  <string>Share Video</string>
  <string>Share Audio</string>
  <string>Toggle Noise Suppression</string>
  <string>Etherpad</string>
  <string>Select Background</string>
  <string>Undock IFrame</string>
  <string>Dock IFrame</string>
  <string>Settings</string>
  <string>Speaker Stats</string>
  <string>View Shortcuts</string>
  <string>Embed Meeting</string>
  <string>Leave Feedback</string>
  <string>Download App</string>
  <string>Help</string>
  <string>Filmstrip</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection toolBarOptions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["toolBarOptions"]));
            }
            set {
                this["toolBarOptions"] = value;
            }
        }
    }
}
